#!/bin/bash
# Regenerates the service Dockerfiles. Keeping them generated from one template
# is what stops the seven of them drifting apart.
set -eu
cd "$(dirname "$0")/../.."

# Every module the parent POM declares. Maven needs each one's POM present in
# the build context even when building a single service, because it reads the
# whole reactor before deciding what to build.
ALL_MODULES="common api-gateway auth-service menu-service order-service \
             payment-service kitchen-service notification-service"

for svc in api-gateway auth-service menu-service order-service \
           payment-service kitchen-service notification-service; do
  case $svc in
    api-gateway)          port=8080 ;;
    auth-service)         port=8081 ;;
    menu-service)         port=8082 ;;
    order-service)        port=8083 ;;
    payment-service)      port=8084 ;;
    kitchen-service)      port=8085 ;;
    notification-service) port=8086 ;;
  esac

  pom_copies=""
  for m in $ALL_MODULES; do
    pom_copies="${pom_copies}COPY services/${m}/pom.xml services/${m}/\n"
  done

  cat > "services/$svc/Dockerfile" <<EOF
# syntax=docker/dockerfile:1.7
# ---------------------------------------------------------------------------
# $svc
#
# Multi-stage. The build stage has Maven and a JDK; the runtime stage has a JRE
# and the application layers, and nothing else — no compiler, no build tools.
#
# Generated by deploy/scripts/gen-dockerfiles.sh. Edit that, not this.
# ---------------------------------------------------------------------------

# --- Build -----------------------------------------------------------------
FROM maven:3.9-eclipse-temurin-21 AS build
WORKDIR /build

# POMs first, as their own layer. They change far less often than source, so
# this layer and the dependency download below are reused on most builds.
# Every module's POM is needed: Maven reads the whole reactor before deciding
# what to build, and a missing one fails the read.
COPY pom.xml .
$(printf "$pom_copies")
RUN --mount=type=cache,target=/root/.m2 \\
    mvn -B -q -pl services/common,services/$svc -am dependency:go-offline -DskipTests || true

COPY services/common/src services/common/src
COPY services/$svc/src services/$svc/src

# -Pfast skips tests: they already ran in CI against this exact commit, and
# running them again here would double the pipeline for no new information.
RUN --mount=type=cache,target=/root/.m2 \\
    mvn -B -q -pl services/common,services/$svc -am package -Pfast

# Spring Boot's own extraction tool splits the fat jar into lib/ (every
# dependency) and a small app.jar whose manifest Class-Path points at it. The
# runtime image copies those as two layers, so a code-only change ships a few
# hundred kilobytes instead of the whole 60 MB jar.
RUN cp services/$svc/target/*.jar /build/app.jar && \\
    java -Djarmode=tools -jar /build/app.jar extract --destination /build/extracted

# --- Runtime ---------------------------------------------------------------
FROM eclipse-temurin:21-jre-alpine AS runtime

# A real system account with a fixed UID, so the Kubernetes securityContext can
# assert runAsUser: 10001 and the two cannot disagree.
RUN addgroup -g 10001 -S dinehub && \\
    adduser -u 10001 -S -G dinehub -h /app -s /sbin/nologin dinehub && \\
    apk add --no-cache curl && \\
    rm -rf /var/cache/apk/*

WORKDIR /app

# Dependencies first: tens of megabytes that change only when a POM changes.
COPY --from=build --chown=10001:10001 /build/extracted/lib/ ./lib/
# Then the application itself: a few hundred kilobytes that change every build.
COPY --from=build --chown=10001:10001 /build/extracted/app.jar ./app.jar

USER 10001:10001
EXPOSE $port

# MaxRAMPercentage rather than a fixed -Xmx: the JVM sizes its heap from the
# container's cgroup limit, so changing the Kubernetes memory limit is enough
# and the two values cannot drift apart.
ENV JAVA_TOOL_OPTIONS="-XX:MaxRAMPercentage=75.0 -XX:InitialRAMPercentage=50.0 -XX:+UseG1GC -XX:+ExitOnOutOfMemoryError -Djava.security.egd=file:/dev/urandom -Dfile.encoding=UTF-8"

# Kubernetes probes are the real health check; this one serves docker compose
# and anyone running the image by hand.
HEALTHCHECK --interval=15s --timeout=3s --start-period=50s --retries=4 \\
  CMD curl -fsS http://localhost:$port/actuator/health/readiness || exit 1

ENTRYPOINT ["java", "-jar", "/app/app.jar"]

LABEL org.opencontainers.image.title="dinehub-$svc" \\
      org.opencontainers.image.description="DineHub $svc" \\
      org.opencontainers.image.source="https://github.com/olivier-ingabire/dinehub-platform" \\
      org.opencontainers.image.licenses="MIT"
EOF
  echo "generated services/$svc/Dockerfile"
done
